version: '3.8'
services:
  mysql:
    image: mysql:8.0  # เลือกเวอร์ชันที่ต้องการ
    container_name: mcs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # กำหนดรหัสผ่าน root
      MYSQL_DATABASE: mcs_db             # กำหนดชื่อฐานข้อมูล
      MYSQL_USER: mcs_user               # กำหนดชื่อผู้ใช้
      MYSQL_PASSWORD: '1234'       # กำหนดรหัสผ่านของผู้ใช้
    ports:
      - "3366:3306"                       # แมปพอร์ต 3306 ของ local กับ container
    volumes:
      - mysql_data:/var/lib/mysql         # ใช้ volume เพื่อเก็บข้อมูลของฐานข้อมูล

volumes:
  mysql_data: