services:
  - type: web  # ระบุว่าเป็นเว็บแอปพลิเคชัน
    name: nestjs-app
    env: node
    branch: main
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: mysql://mcs_user:1234@mysql-service:3306/mcs_db
    regions:
      - singapore
    ports:
      - port: 3000
        protocol: tcp

  - type: database  # ระบุว่าเป็นฐานข้อมูล
    name: mysql-service
    env: docker
    docker:
      image: mysql:8.0
      command:
        - --default-authentication-plugin=mysql_native_password
      envVars:
        - key: MYSQL_ROOT_PASSWORD
          value: root
        - key: MYSQL_DATABASE
          value: mcs_db
        - key: MYSQL_USER
          value: mcs_user
        - key: MYSQL_PASSWORD
          value: 1234
    plan: free